# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

GAEA_COREBASE = '${@os.path.normpath("${LAYERDIR}/")}'

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
